### ISSUE TITLE
Issue with Fetching and Rails 5.0.0.1+

### ISSUE THREAD

**Issue by schneiderderek** [covermymeds/fetching-gem#26]
I've made an example app recreating the issue here: https://github.com/schneiderderek/rails-fetching-gem-issue

TL;DR; rails now calls `#tap` on the object being returned from the action method (e.x. index, show) in the controller. `#tap` on a `Fetching` object does not have the same behavior as a typical Ruby object inheriting from `Object` which causes the issue.

The README in the example rails app has more info.

**Comment by mikegee** [comment]
Thanks Derek. I don’t know why I wasn’t notified when you opened this, or why Github didn’t close it automatically when #27 was merged.
