### ISSUE TITLE
Accessing a key that doesn't exist shouldn't be an error.

### ISSUE THREAD

**Issue by Mysrt** [covermymeds/fetching-gem#28]
Attempting to access a key that doesn't exist in a hash is not an error scenario.  It is a normal usecase of a hash/array.  An error should only be given if an action is taken on the element that didn't exist.

An extension of nilclass should be probably be added that will return the keys available (to the parent) only if a method is called on the nilclass extension.

**Comment by mikegee** [comment]
@Mysrt check out our readme again. You're asking for behavior completely opposed to the point of this gem.

Consider using the `Hashie::Mash` class from [the Hashie gem](https://github.com/intridea/hashie).
